version: "3.8"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: symfony-php
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/symfony"
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: postgres:15
    container_name: symfony-db
    restart: always
    environment:
      POSTGRES_DB: symfonyCv
      POSTGRES_USER: symfonyUser
      POSTGRES_PASSWORD: symfonyPassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: